### PR TITLE
Add support for OsmAnd.

### PR DESCRIPTION
**Pull request by alexsegura**
Hi, 

Thank you for this project 🙂 

A friend is using this app, which seems to be quite popular. 
As it is using Universal Links for iOS, I'm not sure what I need to add in `LSApplicationQueriesSchemes`? Nothing?

### CODE REVIEW

**Comment by alexsegura** [comment]
Ok, now you know I didn't test 😐 

Then, from what I understand, it would be `osmandmaps://` for iOS, and `osmand.geo://` for [Android](https://github.com/osmandapp/Osmand/blob/844f18011190bd3eb2a916971a16440a6ca28734/OsmAnd/AndroidManifest.xml#L452-L456)

**Comment by tschoffelen** [comment]
Cool, you should be able to use [`Platform.select()`](https://reactnative.dev/docs/platform-specific-code#platform-module) to set that URI scheme per platform.

Would you be able to update your PR (and maybe give it a quick check :) )?

**Comment by alexsegura** [comment]
Yes, I'll do this tonight.

**Comment by tschoffelen** [comment]
Released as `react-native-map-link@2.7.12`

**Pull request merged**
