### PR TITLE
Custom Header and Footer Props added to Popup

### PR DESCRIPTION
**Pull request by HanliTheron**
To allow for more flexibility a custom header and footer prop can be added. This allows the developer the freedom to use their own components in the Modal if necessary.

### CODE REVIEW

**Comment by tschoffelen** [comment]
Looks great!

Before I merge this, would you mind adding these new props to the [index.d.ts](https://github.com/tschoffelen/react-native-map-link/blob/master/index.d.ts) Typescript definition file? Thanks!

**Comment by HanliTheron** [comment]
@tschoffelen Ah thanks. Sorry I'm not used to typescript. I made the changes.

**Comment by tschoffelen** [comment]
Perfect! Thanks for your contribution.

Released to NPM as `react-native-map-link@2.7.7`

**Comment by HanliTheron** [comment]
Awesome, thanks!

**Pull request merged**
